package _03_To_Do_List;

class RunRunRun {
	public static void main(String[] args) {
		ToDoList runrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrun = new ToDoList();
		runrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrunrunrunrurnurnrunrurnurnrunrurnurnurnrunrunrunrunrun
				.run();
	}
}
